### PR TITLE
Add event callback to solver backend to monitor progress

### PR DESCRIPTION
**Pull request by tlambert03**
This pull request adds an event callback feature to the SolverBackend class, and exposes it on the ilpy.Solver object with `set_event_callback()`.  (currently only implemented for the SCIP backend)

This takes a python callable that will be called with a mapping of key/value metadata for each event that occurs during the solving process.  Structure of that payload, and exact events that occur remain to be seen.  However, as a current example, the following script:

```python
import ilpy
import numpy as np

N = 100

solution = ilpy.solve(
    objective=list(range(1, N + 1)),
    constraints=(
        [(row.tolist(), "<=", 1) for row in np.eye(N)] + [([1] * N, "=", N // 2)]
    ),
    sense=ilpy.Sense.Minimize,
    variable_type=ilpy.VariableType.Binary,
    preference=ilpy.Preference.Scip,
    on_event=print,
)
```

would print out 

```python
{'dualbound': -1e+20, 'event_type': 'PRESOLVEROUND', 'gap': 1e+20, 'primalbound': 1e+20}
{'dualbound': -1e+20, 'event_type': 'PRESOLVEROUND', 'gap': 1e+20, 'primalbound': 1e+20}
{'dualbound': -1e+20, 'event_type': 'PRESOLVEROUND', 'gap': 1e+20, 'primalbound': 1e+20}
{'dualbound': -1e+20, 'event_type': 'PRESOLVEROUND', 'gap': 1e+20, 'primalbound': 1e+20}
{'dualbound': -1e+20, 'event_type': 'PRESOLVEROUND', 'gap': 1e+20, 'primalbound': 1e+20}
{'dualbound': -1e+20, 'event_type': 'NODEDELETE', 'gap': 1e+20, 'primalbound': 1e+20}
{'dualbound': -1e+20, 'event_type': 'NODEFOCUSED', 'gap': 1e+20, 'primalbound': 1e+20}
{'dualbound': 0.0, 'event_type': 'BESTSOLFOUND', 'gap': 1e+20, 'primalbound': 1985.0}
{'dualbound': 0.0, 'event_type': 'FIRSTLPSOLVED', 'gap': 1e+20, 'primalbound': 1985.0}
{'dualbound': 1275.0, 'event_type': 'BESTSOLFOUND', 'gap': 0.0, 'primalbound': 1275.0}
{'dualbound': 1275.0, 'event_type': 'NODEINFEASIBLE', 'gap': 0.0, 'primalbound': 1275.0}
{'dualbound': 1275.0, 'event_type': 'NODEINFEASIBLE', 'gap': 0.0, 'primalbound': 1275.0}
{'dualbound': 1275.0, 'event_type': 'NODEDELETE', 'gap': 0.0, 'primalbound': 1275.0}
```

( not a very interesting one since it gets solved in one step)...

### CODE REVIEW

**Comment by tlambert03** [comment]
@funkey, curious to get your initial thoughts on this

**Comment by tlambert03** [comment]
callbacks working for gurobi now as well, with dualbound, primalbound and gap reported for each backend.  The remainder of the work now is in
- deciding exactly what data we want to emit (i.e. do we want to grab things in addition to dual/primal bound)
- deciding whether/how to notify on events unrelated to solving, such as presolving events
- optimizing the event callback connections in both backends to emit "enough" but not too much

**Comment by tlambert03** [comment]
note also @funkey , I've bumped this to c++17 to use  `std::variant` ... but can find an alternative if you'd prefer to keep it at c++1

**Comment by funkey** [comment]
Wonderful, this is great! :)

No problem with C++17. Looks all good to me. Thanks a lot!

**Pull request merged**
